/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinkCreateRouteImport } from './routes/link.create'
import { Route as LinkIdEditRouteImport } from './routes/link.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkCreateRoute = LinkCreateRouteImport.update({
  id: '/link/create',
  path: '/link/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkIdEditRoute = LinkIdEditRouteImport.update({
  id: '/link/$id/edit',
  path: '/link/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/link/create': typeof LinkCreateRoute
  '/link/$id/edit': typeof LinkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/link/create': typeof LinkCreateRoute
  '/link/$id/edit': typeof LinkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/link/create': typeof LinkCreateRoute
  '/link/$id/edit': typeof LinkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/link/create' | '/link/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/link/create' | '/link/$id/edit'
  id: '__root__' | '/' | '/link/create' | '/link/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinkCreateRoute: typeof LinkCreateRoute
  LinkIdEditRoute: typeof LinkIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link/create': {
      id: '/link/create'
      path: '/link/create'
      fullPath: '/link/create'
      preLoaderRoute: typeof LinkCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link/$id/edit': {
      id: '/link/$id/edit'
      path: '/link/$id/edit'
      fullPath: '/link/$id/edit'
      preLoaderRoute: typeof LinkIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinkCreateRoute: LinkCreateRoute,
  LinkIdEditRoute: LinkIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
